language: python
sudo: false
python:
  - "3.5"
virtualenv:
  system_site_packages: false
before_install:
- mkdir -p $HOME/bin
- wget https://github.com/git-lfs/git-lfs/releases/download/v1.5.5/git-lfs-linux-amd64-1.5.5.tar.gz
- tar xvfz git-lfs-linux-amd64-1.5.5.tar.gz
- mv git-lfs-1.5.5/git-lfs $HOME/bin/git-lfs
- export PATH=$PATH:$HOME/bin/
install:
  - export CONDA=$HOME/miniconda
  - export PATH="$CONDA/bin:$PATH"
  # install conda, but only if it doesn't already exist
  - command -v conda > /dev/null || {
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -f -p $CONDA; }
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # try to create env, but ignore if it fails -- probably cached.
  - conda env create -q -f test-environment.yml || true
  - source activate skantest
  - conda info -a

  # install coveralls for reporting
  - pip install coveralls

  # Install gala
  - printenv PWD
  # Build locally, pytest confuses local and global installs
  - pip install -e .

before_script:
  - git lfs fetch

script:
  # Run tests
  - export MPLBACKEND="ps"
  - python -c 'import matplotlib.pyplot as plt; print(plt.get_backend())'
  - py.test

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then make numba-clean; export NUMBA_DISABLE_JIT=1; py.test --cov-report term-missing --cov .; coveralls; fi

cache:
    directories:
        - $HOME/miniconda
        - $HOME/.matplotlib
