name: skantest
dependencies:
- python>=3.5*
- setuptools>=19.6*
- numba>=0.29
- numpy>=1.11*
- numpydoc>=0.5*
- scipy>=0.18*
- networkx>=1.11*
- matplotlib>=1.5*
- scikit-image>=0.12*
- pandas>=0.18*
- pytest>=3*
- coverage>=4.0
- pytest-cov>=2.2
pip:
  - hypothesis>=3.6
